### ISSUE TITLE
Python wrapper crashes matplotlib/python when imported and used before pyplot

### ISSUE THREAD

**Issue by wouterbulten** [GeertLitjens/ASAP#34]
When the python wrapper is imported and used before matplotlib is imported, every plot call to matplotlib crashes the python process. My guess is that the python wrapper somehow prevents matplotlib loading the correct Qt backend. It is a minor issue as loading all modules first does not trigger the problem. Nonetheless, in interactive sessions users will expect that the order of imports does not matter. 

Debugging gives the following exception:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2017.1\helpers\pydev\pydevd.py", line 1578, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2017.1\helpers\pydev\pydevd.py", line 1015, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:/Projects/prostate-epithelium-segmentation/main.py", line 70, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\wouterbulten\Anaconda2\envs\cadcourse\lib\site-packages\matplotlib\pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "C:\Users\wouterbulten\Anaconda2\envs\cadcourse\lib\site-packages\matplotlib\backends\__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "C:\Users\wouterbulten\Anaconda2\envs\cadcourse\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore
  File "C:\Users\wouterbulten\Anaconda2\envs\cadcourse\lib\site-packages\matplotlib\backends\backend_qt5.py", line 26, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "C:\Users\wouterbulten\Anaconda2\envs\cadcourse\lib\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "C:\Users\wouterbulten\Anaconda2\envs\cadcourse\lib\site-packages\matplotlib\backends\qt_editor\formlayout.py", line 56, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "C:\Users\wouterbulten\Anaconda2\envs\cadcourse\lib\site-packages\matplotlib\backends\qt_compat.py", line 137, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named PyQt4
```

As Qt5 is installed there is no need for matplotlib to load Qt4.

**Code example that tiggers error:**

```python
import multiresolutionimageinterface as mrimage

reader = mrimage.MultiResolutionImageReader()
img = reader.open( ... some path ..)

import matplotlib.pyplot as plt
plt.plot(range(10))
```

**Code that works:**

```python

import matplotlib.pyplot as plt
import multiresolutionimageinterface as mrimage
reader = mrimage.MultiResolutionImageReader()
img = reader.open( ... some path ..)

plt.plot(range(10))
```

Setting the backend explictely in a interactive session (i.e. `%matplotlib qt5`) also solves the problem.

**Comment by GeertLitjens** [comment]
I cannot reproduce this on my machine, is this still an issue?

**Comment by wouterbulten** [comment]
Did you test it in Spyder or in a standalone python script? Because Spyder will automatically set everything correctly (as does a Jupyter notebook). The problem only occurs in a standalone script or when running from a IDE that does not set the backend explicitly.

(Disclaimer: I did not yet test it with the newest python 3.5 build, but I can try to reproduce it in that version)

**Comment by GeertLitjens** [comment]
I tested it with ipython on Python 3.5 under Linux and indeed with Spyder under Windows

**Comment by wouterbulten** [comment]
The error is still there (tested under Python 3.5 using PyCharm and standalone in a shell on Windows). Minimal code that triggers it:

```python
import multiresolutionimageinterface as mrimage

reader = mrimage.MultiResolutionImageReader()
img = reader.open('D:/Data/SPIE18/slides/T12-18345-7_01_APERIO.svs')
import matplotlib.pyplot as plt
```

Error:   
````
 from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: DLL load failed: The specified procedure could not be found.
````

**Comment by GeertLitjens** [comment]
Probably the Qt5 DLLs used by the wrapper are compiled with a newer version of MSVC which is not backward compatible with the ones used by matplotlib. The other way around is probably ok, which is why loading matplotlib first works. I don't have a good solution for this except removing the Qt5 DLLs from the multiresolutionimageinterface folder (ASAP will no longer work, but the wrapper will). Then you can make a separate install for ASAP.
